# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python_list\add_text.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_text(object):
    def setupUi(self, Add_text):
        Add_text.setObjectName("Add_text")
        Add_text.resize(507, 181)
        self.textEdit = QtWidgets.QTextEdit(Add_text)
        self.textEdit.setGeometry(QtCore.QRect(120, 40, 340, 50))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Add_text)
        self.label.setGeometry(QtCore.QRect(30, 40, 72, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Add_text)
        self.pushButton.setGeometry(QtCore.QRect(120, 110, 340, 30))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Add_text)
        QtCore.QMetaObject.connectSlotsByName(Add_text)

    def retranslateUi(self, Add_text):
        _translate = QtCore.QCoreApplication.translate
        Add_text.setWindowTitle(_translate("Add_text", "Form"))
        self.label.setText(_translate("Add_text", "添加文本"))
        self.pushButton.setText(_translate("Add_text", "PushButton"))

if __name__ == "__main__":
    text_window = Ui_Add_text()
    text_window.setupUi(text_window)